/* ***********************************************
 * lyngdorf_server
 * by drdude684
*/

// DO NOT EDIT this file. Copy it to 'myconfig.js' and adjust to your preference
exports.debug = true;  // show debugging msgs
exports.ip = "localhost";  // IP address to listen on, defaults to host name
exports.port = 8008;  // port to listen on, defaults to 80
exports.lyngdorfaddress = 'tdai1120.local' // IP address of lyngdorf device

